[general]
live_config_reload = true
working_directory = "None"

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false
decorations = "Full"
opacity = 0.9
padding.x = 5
padding.y = 5

[cursor.style]
shape= "Beam"
blinking = "Never"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[terminal.shell]
program = "/bin/bash"
args = []

[scrolling]
history = 10000